### ISSUE TITLE
Allow getting out of maintenance mode after loading the database sql.

### ISSUE THREAD

**Issue by a-t-0** [HiveMinds/nextcloudq#1]
#### Describe the bug
Nextcloud is not able to pull out of maintenance mode after importing the `database.sql`:
> Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'oc_root'@'localhost' (using password: YES) in /snap/nextcloud/33054/htdocs/lib/private/DB/Connection.php:139

Probably because I am doing something wrong with the nextcloud mysql user, or permissions.

#### To Reproduce
```
git clone https://github.com/HiveMinds/Collabora-Online.git
cd Collabora-Online
chmod +x *.sh
src/main.sh -un # uninstall Nextcloud
src/main.sh -i # install Tor and Nextcloud
src/main.sh -cn # Configure nextcloud
src/main.sh -cs # Enable the Nextcloud Calendar application.
src/main.sh -h # Setup https/ssl and make firefox trust it.

cd ..
git clone https://github.com/HiveMinds/nextcloudq
sudo src/import-export/bin/export-data 
sudo src/import-export/bin/import-data ~!/git/backup0/20230*



```
or try: `sudo src/import-export/bin/import-data ~/git/backup0/20230127-034839` where you replace the date with the backup you created

#### Expected behavior
Would expect the backup to be restored and Nextcloud successfully out of maintenance mode.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud

and:

    $ snap version

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

$sudo src/import-export/bin/import-data /home/name/git/backup0/20230127-034839
WARNING: This functionality is still experimental and under
development, use at your own risk. Note that the CLI interface is
unstable, so beware if using from within scripts.

src/import-export/bin/import-data: 24: occ: not found
Clearing existing non-default apps... done
Importing apps...
         52,15M 100%  365,43MB/s    0:00:00 (xfr#762, to-chk=0/787)  
Dropping existing database... done
Creating new database... done
Granting database privileges to existing user... done
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1410 (42000) at line 1: You are not allowed to create a user with GRANT
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'oc_root'@'127.0.0.1'
Granting database privileges to existing nextcloud user... done
mysql: [Warning] Using a password on the command line interface can be insecure.
Importing database...
mysql: [Warning] Using a password on the command line interface can be insecure.
database_password=yEZNeb3gCZwjowGaD7mJtJ2mhQEDSX-QrEjY0Fj6B2-U61BBLg1udyzmKZ7fDLX1
Importing config...
Clearing existing data... done
Importing data...
         28,20M 100%  413,70MB/s    0:00:00 (xfr#37, to-chk=0/48) 
Disabling maintenance mode... error
An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'oc_root'@'localhost' (using password: YES) in /snap/nextcloud/33054/htdocs/lib/private/DB/Connection.php:139
Stack trace:
#0 /snap/nextcloud/33054/htdocs/3rdparty/doctrine/dbal/src/Connection.php(1519): OC\DB\Connection->connect()
#1 /snap/nextcloud/33054/htdocs/3rdparty/doctrine/dbal/src/Connection.php(1041): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /snap/nextcloud/33054/htdocs/lib/private/DB/Connection.php(261): Doctrine\DBAL\Connection->executeQuery()
#3 /snap/nextcloud/33054/htdocs/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(345): OC\DB\Connection->executeQuery()
#4 /snap/nextcloud/33054/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php(281): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /snap/nextcloud/33054/htdocs/lib/private/AppConfig.php(415): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /snap/nextcloud/33054/htdocs/lib/private/AppConfig.php(180): OC\AppConfig->loadConfigValues()
#7 /snap/nextcloud/33054/htdocs/lib/private/AppConfig.php(371): OC\AppConfig->getApps()
#8 /snap/nextcloud/33054/htdocs/lib/private/legacy/OC_App.php(965): OC\AppConfig->getValues()
#9 /snap/nextcloud/33054/htdocs/lib/private/Server.php(725): OC_App::getAppVersions()
#10 /snap/nextcloud/33054/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}()
#11 /snap/nextcloud/33054/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /snap/nextcloud/33054/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet()
#13 /snap/nextcloud/33054/htdocs/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#14 /snap/nextcloud/33054/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#15 /snap/nextcloud/33054/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(184): OC\AppFramework\Utility\SimpleContainer->get()
#16 /snap/nextcloud/33054/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#17 /snap/nextcloud/33054/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#18 /snap/nextcloud/33054/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet()
#19 /snap/nextcloud/33054/htdocs/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#20 /snap/nextcloud/33054/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#21 /snap/nextcloud/33054/htdocs/lib/private/Server.php(1119): OC\AppFramework\Utility\SimpleContainer->get()
#22 /snap/nextcloud/33054/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}()
#23 /snap/nextcloud/33054/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#24 /snap/nextcloud/33054/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet()
#25 /snap/nextcloud/33054/htdocs/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#26 /snap/nextcloud/33054/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#27 /snap/nextcloud/33054/htdocs/lib/private/Server.php(2070): OC\AppFramework\Utility\SimpleContainer->get()
#28 /snap/nextcloud/33054/htdocs/lib/private/Files/View.php(117): OC\Server->getLockingProvider()
#29 /snap/nextcloud/33054/htdocs/lib/private/Server.php(462): OC\Files\View->__construct()
#30 /snap/nextcloud/33054/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}()
#31 /snap/nextcloud/33054/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#32 /snap/nextcloud/33054/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet()
#33 /snap/nextcloud/33054/htdocs/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#34 /snap/nextcloud/33054/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#35 /snap/nextcloud/33054/htdocs/lib/private/Server.php(1472): OC\AppFramework\Utility\SimpleContainer->get()
#36 /snap/nextcloud/33054/htdocs/lib/base.php(617): OC\Server->boot()
#37 /snap/nextcloud/33054/htdocs/lib/base.php(1144): OC::init()
#38 /snap/nextcloud/33054/htdocs/console.php(48): require_once('...')
#39 /snap/nextcloud/33054/htdocs/occ(11): require_once('...')
#40 {main}
(base) name@name ~/git/nextcloudq

**Comment by a-t-0** [comment]
Done. it is the configuration that yields the error.
